insert into books (productID, productName, productDescription, Quantity) values ('709937816-3', 'Number One with a Bullet', 'Excision of Facial Muscle, Perc Endo Approach, Diagn', 1);
insert into books (productID, productName, productDescription, Quantity) values ('398019457-4', 'Passchendaele', 'Revision of Intraluminal Device in Ureter, External Approach', 2);
insert into books (productID, productName, productDescription, Quantity) values ('295543079-X', 'Buffalo Girls', 'Removal of Nonaut Sub from R Rib, Perc Endo Approach', 3);
insert into books (productID, productName, productDescription, Quantity) values ('286035565-0', 'Welcome Farewell-Gutmann (Bienvenido a Farewell-Gutmann)', 'Excision of Inferior Mesenteric Artery, Perc Approach', 4);
insert into books (productID, productName, productDescription, Quantity) values ('716424180-5', 'It''s My Mother''s Birthday Today', 'Supplement Right Foot Vein with Autol Sub, Perc Approach', 5);
insert into books (productID, productName, productDescription, Quantity) values ('421299708-8', 'Rapture-Palooza', 'Revision of Nonaut Sub in L Carpal Jt, Perc Approach', 6);
insert into books (productID, productName, productDescription, Quantity) values ('140805592-9', 'Burning Blue', 'Excision of Right Ovary, Open Approach, Diagnostic', 7);
insert into books (productID, productName, productDescription, Quantity) values ('375899948-0', 'Midnight Bayou', 'Reattachment of Right Trunk Tendon, Perc Endo Approach', 8);
insert into books (productID, productName, productDescription, Quantity) values ('535503111-0', 'Hitch', 'Extirpation of Matter from Head Lymphatic, Perc Approach', 9);
insert into books (productID, productName, productDescription, Quantity) values ('580620909-1', 'Ego', 'Supplement R Finger Phalanx with Nonaut Sub, Open Approach', 10);
insert into books (productID, productName, productDescription, Quantity) values ('403026033-0', 'Fistful of Fingers, A', 'Drainage of Right Elbow Joint with Drain Dev, Open Approach', 11);
insert into books (productID, productName, productDescription, Quantity) values ('320323934-5', 'Bundle of Joy', 'Removal of Synthetic Substitute from Nose, External Approach', 12);
insert into books (productID, productName, productDescription, Quantity) values ('772784580-9', 'Giger''s Necronomicon', 'Remove of Spacer from L Metatarsotars Jt, Perc Endo Approach', 13);
insert into books (productID, productName, productDescription, Quantity) values ('357105534-9', 'Alley Cats, The', 'Fusion of Coccygeal Joint with Synth Sub, Perc Endo Approach', 14);
insert into books (productID, productName, productDescription, Quantity) values ('448687631-8', 'To Kill a Priest', 'Restrict of L Subclav Vein with Intralum Dev, Open Approach', 15);
insert into books (productID, productName, productDescription, Quantity) values ('931463861-8', 'Taste the Blood of Dracula', 'Chiropractic Manipulation of Pelvis, Long, Short Lever', 16);
insert into books (productID, productName, productDescription, Quantity) values ('497367273-4', 'Red Flag', 'Resection of Head Muscle, Open Approach', 17);
insert into books (productID, productName, productDescription, Quantity) values ('398255007-6', 'Little Stiff, A', 'Restriction of Left Upper Lobe Bronchus, Perc Endo Approach', 18);
insert into books (productID, productName, productDescription, Quantity) values ('869383777-X', 'Männerherzen... und die ganz ganz große Liebe', 'Repair Left Index Finger, Percutaneous Approach', 19);
insert into books (productID, productName, productDescription, Quantity) values ('975786435-8', 'Sessions, The (Surrogate, The)', 'Beam Radiation of Adrenal Glands using Photons 1 - 10 MeV', 20);
insert into books (productID, productName, productDescription, Quantity) values ('542495889-3', 'Fido', 'Drainage of Greater Omentum, Percutaneous Approach, Diagn', 21);
insert into books (productID, productName, productDescription, Quantity) values ('024584763-4', 'Free Ride', 'Restriction of Carina, Percutaneous Endoscopic Approach', 22);
insert into books (productID, productName, productDescription, Quantity) values ('324382592-X', 'Piano in a Factory, The (Gang de qin)', 'Repair Left Maxillary Sinus, Open Approach', 23);
insert into books (productID, productName, productDescription, Quantity) values ('893763098-2', 'Ben-Hur: A Tale of the Christ', 'Remove Infusion Dev from R Metatarsotars Jt, Extern', 24);
insert into books (productID, productName, productDescription, Quantity) values ('407792301-8', 'City Girl', 'Supplement Nasal Turbinate with Synth Sub, Perc Approach', 25);
insert into books (productID, productName, productDescription, Quantity) values ('477441510-3', 'Hidden Face, The (La cara oculta)', 'Revision of Drainage Device in Right Breast, Perc Approach', 26);
insert into books (productID, productName, productDescription, Quantity) values ('673335431-4', 'Fall of the House of Usher, The (Zánik domu Usheru)', 'Repair Left Ankle Region, Open Approach', 27);
insert into books (productID, productName, productDescription, Quantity) values ('033191021-7', 'Rains Came, The', 'Replace of Esophageal Vein with Nonaut Sub, Open Approach', 28);
insert into books (productID, productName, productDescription, Quantity) values ('437428322-6', 'Wu yen', 'Occlusion of Low Art with Intralum Dev, Perc Endo Approach', 29);
insert into books (productID, productName, productDescription, Quantity) values ('810580642-8', 'October Baby', 'Bypass Jejunum to Anus with Nonaut Sub, Open Approach', 30);
